### ISSUE TITLE
Update Rate This Page thank you message text

### ISSUE THREAD

**Issue by chrisrhymes** [FutureNorthants/northants-design-system#505]
In the thank you message text, can we remove the text saying we will reply within 5 days. 

Please replace it with 'Thank you for your feedback. Your comments will help us to improve the website.'

**Comment by chrisrhymes** [comment]
@LucyCox24 is this ok?


![Image](https://github.com/user-attachments/assets/2c795c4d-1b63-405e-8f9f-9060e9730862)

**Comment by LucyCox24** [comment]
@chrisrhymes yes this is perfect, thank you
